### PR TITLE
Verilator lint fixes

### PR DESCRIPTION
**Pull request by marnovandermaas**
This PR fixes various problems picked up by browsing Verilator lint warnings. Please have a look at the individual commit messages for details of why the changes were made.

### CODE REVIEW

**Comment by marnovandermaas** [comment]
Converting this PR to draft until I fix some build issues that I am facing with Vivado.

**Comment by marnovandermaas** [comment]
@microsoft-github-policy-service agree company="lowRISC"

**Comment by marnovandermaas** [comment]
The issues I mentioned before should now be resolved. Before mergin, please have a look at commit: https://github.com/microsoft/cheriot-ibex/pull/19/commits/fe2147062e1b479035ed1be2b3f3eb6cc8a8d9d7
I think this is the right approach but it does create a slight change in behavior on reset. I don't think this is a problem, but it would be good to get a second opinion.

**Comment by kliuMsft** [comment]
Thanks - sorry for the delayed response and I will look into it. I haven't been ignoring this but just a little swamped recently. We may have to do a manual merge this time since there are a few more updates on my side as well.

**Comment by marnovandermaas** [comment]
I'm converting this to draft because commit: https://github.com/microsoft/cheriot-ibex/pull/19/commits/fe2147062e1b479035ed1be2b3f3eb6cc8a8d9d7 breaks behavior of `csetboundsexact`.

**Comment by marnovandermaas** [comment]
I've removed two commits from this PR because of recent changes and to revert a change in behavior. This should now be ready for review.

**Review by kliuMsft — APPROVED** [review]

**Pull request merged**
