### PR TITLE
Base correction only needs one bit

### PR DESCRIPTION
**Pull request by marnovandermaas**
This saves one bit per register without any performance loss.

### CODE REVIEW

**Comment by marnovandermaas** [comment]
Pushed a minor fix and doesn't seem to break anything as far as I'm aware so marking this as ready for review.

**Comment by marnovandermaas** [comment]
I tested this by running the Sonata CI tests on it as well as the CHERIoT RTOS test suite.

**Comment by marnovandermaas** [comment]
Ok, after making changes to the data type invariant, which uses the reg_cap_t that was changed, all the proofs successfully succeed.

**Comment by kliuMsft** [comment]
Cool. We are actually in the middle of making a couple of the last v1.0 changes. Will try to merge this one after that.

**Comment by marnovandermaas** [comment]
Sounds good, thanks Kunyan.

**Review by kliuMsft — APPROVED** [review]

**Pull request merged**
